//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTask.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int id { get; set; }
        public int o_id { get; set; }
        public int p_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
